### ISSUE TITLE
Make Blocks Responsive

### ISSUE THREAD

**Issue by dmitriiii** [Fancy-nerds/fancynerds#3]
- [x] about (@Delave-las-Kure)
- [x] faq-list  (@Delave-las-Kure)
- [x] seo-form (@Delave-las-Kure)
- [x] testimonials (@Delave-las-Kure)
- [x] action (@Delave-las-Kure)
- [x] jumbotron (@Delave-las-Kure)
- [x] services (@Delave-las-Kure)
- [x] testimonials-slider (@Delave-las-Kure)
- [x] advantages (@Delave-las-Kure)
- [x] jumbotron__inner (@Delave-las-Kure)
- [x] services-list (@Delave-las-Kure)
- [x] what-is (@Delave-las-Kure)
- [x] benefits (@Delave-las-Kure)
- [x] numbers (@Delave-las-Kure )
- [x] skills (@Delave-las-Kure)
- [x] who-we-are  (@Delave-las-Kure)
- [x] blog (@Delave-las-Kure)
- [x] partners (@Delave-las-Kure)
- [x] steps (@Delave-las-Kure)
- [x] why-choose (@Delave-las-Kure)
- [x] cases-slider (@Delave-las-Kure)
- [x] plans (@Delave-las-Kure)
- [x] support (@Delave-las-Kure)
- [x] support form (@Delave-las-Kure)
- [ ] ~~comments~~
- [x] principles (@Delave-las-Kure)
- [x] team-slider (@Delave-las-Kure)
- [x] counters (@Delave-las-Kure)
- [x] results (@Delave-las-Kure)
- [x] team__photo (@Delave-las-Kure)
- [x] team [shortcode] (@Delave-las-Kure)
- [x] team:teamplate (@Delave-las-Kure)
- [x] header (@Delave-las-Kure)

**Comment by Delave-las-Kure** [comment]
Ребят, никогда не вешайте на body и html overflow hidden. Don’t be a dick.
